apiVersion: apps/v1
kind: Deployment
metadata:
  name: makecoffee
  labels:
    app: makecoffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makecoffee
  template:
    metadata:
      labels:
        app: makecoffee
    spec:
      containers:
        - name: makecoffee
          image: username/makecoffee:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5